### ISSUE TITLE
Not compatible with PHP 8.x

### ISSUE THREAD

**Issue by uberhacker** [bluecadet/bluecadet_utilities#28]
Error from `composer install` below:
```
bluecadet/bluecadet_utilities[v3.0.0, ..., v3.0.1] require php ^5.3.3 || ^7.0 -> your php version (8.1.10) does not satisfy that requirement.
```

**Comment by pingevt** [comment]
@uberhacker - You'll want to bump it to v4

`composer require bluecadet/bluecadet_utilities": "4.0.x-dev`

Theres not much to it other than allowing php 8 and Its been working for us for a few months, so I can commit an official release in a moment if you don't want a dev branch. Keep an eye out for 4.0.1 at [packagist](https://packagist.org/packages/bluecadet/bluecadet_utilities#4.0.x-dev)

**Comment by uberhacker** [comment]
Hey @pingevt:  Appreciate the quick feedback.  Yeah, what threw me off is the master branch still doesn't have `^8.0` in composer.json yet.
